# Generated by Django 3.1.3 on 2022-07-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremodel',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genremodel',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='moviesmodel',
            old_name='genre',
            new_name='Genre',
        ),
    ]
