# Generated by Django 3.1.3 on 2022-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220709_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesId',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='genremodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
