# Generated by Django 3.1.3 on 2022-07-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20220709_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremodel',
            old_name='genre',
            new_name='Genre',
        ),
    ]
